export const nodes = [
  {
    id: 'i0',
    type: 'inputNode',
    data: { name: 'Select-Option', label: 'S_WERKS', description: 'Plant' },
    position: { x: 0, y: 80 },
  },
  {
    id: 'i1',
    type: 'inputNode',
    data: {
      name: 'Select-Option',
      label: 'S_MATNR',
      description: 'Material',
    },
    position: { x: 0, y: 200 },
  },
  {
    id: 'i2',
    type: 'inputNode',
    data: { name: 'Checkbox', label: 'P_OUT', description: 'Display Output' },
    position: { x: 0, y: 500 },
  },
  {
    id: 'q0',
    type: 'queryNode',
    data: {
      name: 'Query',
      label: 'MARC',
      inputs: [
        { label: 'MATNR', description: 'Material', type: 'data' },
        { label: 'WERKS', description: 'Plant', type: 'data' },
      ],
      outputs: [
        { label: 'MATNR', description: 'Material', type: 'data' },
        { label: 'WERKS', description: 'Plant', type: 'data' },
      ],
    },
    position: { x: 250, y: 10 },
  },

  {
    id: 'q1',
    type: 'queryNode',
    data: {
      name: 'Query',
      label: 'MARA',
      inputs: [{ label: 'MATNR', description: 'Material', type: 'data' }],
      outputs: [
        { label: 'MATNR', description: 'Material', type: 'data' },
        { label: 'ERSDA', description: 'Created On', type: 'data' },
        { label: 'ERNAM', description: 'Created By', type: 'data' },
        { label: 'LAEDA', description: 'Changed On', type: 'data' },
      ],
    },
    position: { x: 250, y: 240 },
  },
  {
    id: 'q2',
    type: 'queryNode',
    data: {
      name: 'Query Post Processing',
      label: 'Output',
      inputs: [{ label: '+', type: 'data' }],
      outputs: [
        { label: 'MATNR', description: 'Material', type: 'data' },
        { label: 'WERKS', description: 'Plant', type: 'data' },
        { label: 'ERSDA', description: 'Created On', type: 'data' },
        { label: 'ERNAM', description: 'Created By', type: 'data' },
        { label: 'LAEDA', description: 'Changed On', type: 'data' },
      ],
    },
    position: { x: 500, y: 120 },
  },
  {
    id: 'o0',
    type: 'outputNode',
    data: {
      name: 'Output',
      label: 'ALV Hierarchical Display',
      header: [{ label: 'WERKS', description: 'Plant', type: 'data' }],
      items: [
        { label: 'MATNR', description: 'Material', type: 'data' },
        { label: 'ERSDA', description: 'Created On', type: 'data' },
        { label: 'ERNAM', description: 'Created By', type: 'data' },
        { label: 'LAEDA', description: 'Changed On', type: 'data' },
      ],
      controllers: [{ label: 'OUT', description: 'Display On/Off', type: 'data' }],
    },
    position: { x: 900, y: 180 },
  },
];

export const edges = [
  {
    id: 'e0-1',
    source: 'i0',
    sourceHandle: 'o__data',
    target: 'q0',
    targetHandle: 'i-MATNR__data',
    animated: false,
  },
  {
    id: 'e0-2',
    source: 'i1',
    sourceHandle: 'o__data',
    target: 'q0',
    targetHandle: 'i-WERKS__data',
    animated: false,
  },
  {
    id: 'e0-3',
    source: 'i1',
    sourceHandle: 'o__data',
    target: 'q1',
    targetHandle: 'i-MATNR__data',
    animated: false,
  },
  {
    id: 'e0-4',
    source: 'q0',
    sourceHandle: 'o-MATNR__data',
    target: 'q2',
    targetHandle: 'i',
    animated: false,
  },
  {
    id: 'e0-5',
    source: 'q0',
    sourceHandle: 'o-WERKS__data',
    target: 'q2',
    targetHandle: 'i-data',
    animated: false,
  },
  {
    id: 'e0-6',
    source: 'q1',
    sourceHandle: 'o-MATNR__data',
    target: 'q2',
    targetHandle: 'i-data',
    animated: false,
  },
  {
    id: 'e0-8',
    source: 'q1',
    sourceHandle: 'o-ERSDA__data',
    target: 'q2',
    targetHandle: 'i-data',
    animated: false,
  },
  {
    id: 'e0-9',
    source: 'q1',
    sourceHandle: 'o-ERNAM__data',
    target: 'q2',
    targetHandle: 'i-data',
    animated: false,
  },
  {
    id: 'e0-10',
    source: 'q1',
    sourceHandle: 'o-LAEDA__data',
    target: 'q2',
    targetHandle: 'i-data',
    animated: false,
  },
  {
    id: 'e0-11',
    source: 'q2',
    sourceHandle: 'o-MATNR__data',
    target: 'o0',
    targetHandle: 'i-MATNR__data',
    animated: false,
  },
  {
    id: 'e0-12',
    source: 'q2',
    sourceHandle: 'o-WERKS__data',
    target: 'o0',
    targetHandle: 'h-WERKS__data',
    animated: false,
  },
  {
    id: 'e0-13',
    source: 'q2',
    sourceHandle: 'o-ERSDA__data',
    target: 'o0',
    targetHandle: 'i-ERSDA__data',
    animated: false,
  },
  {
    id: 'e0-14',
    source: 'q2',
    sourceHandle: 'o-ERNAM__data',
    target: 'o0',
    targetHandle: 'i-ERNAM__data',
    animated: false,
  },
  {
    id: 'e0-15',
    source: 'q2',
    sourceHandle: 'o-LAEDA__data',
    target: 'o0',
    targetHandle: 'i-LAEDA__data',
    animated: false,
  },
  {
    id: 'e0-16',
    source: 'i2',
    sourceHandle: 'o__data',
    target: 'o0',
    targetHandle: 'c-OUT__data',
    animated: false,
  },
];
